### ISSUE TITLE
Report error.

### ISSUE THREAD

**Issue by ChangJoo-Park** [careteditor/issues#339]
The following error has occurred:
```
{
    "message": "this[_0x7f2e[55]][_0x7f2e[179]] is not a function",
    "version": "2.0.11",
    "os": "macOS Sierra",
    "path": "web/Editor/Editor.Code.js",
    "code": "this[_0x7f2e[55]][_0x7f2e[179]](this[_0x7f2e[54]][_0x7f2e[30]](",
    "line": 5,
    "column": 35530,
    "stack": [
        "at _0x352bx2.value (web/Editor/Editor.Code.js:5:35530)",
        "at t.value (web/Events.js:5:1330)",
        "at t.value (web/Extension.Command.js:5:2297)",
        "at t.value (web/Extension.Command.js:5:2554)"
    ]
}
```

**Comment by astoilkov** [comment]
Hi @ChangJoo-Park,

Thanks for reporting. Do you know what action caused the error?

Thanks in advance.

**Comment by ChangJoo-Park** [comment]
@astoilkov Hello.
When I editing [this file](https://github.com/vuejs/vue-loader/blob/master/docs/kr/configurations/extract-css.md)
